# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvillemi <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/10/16 18:06:32 by mvillemi          #+#    #+#              #
#    Updated: 2017/10/16 18:08:36 by mvillemi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ifndef CUR_PROJECT_PWD
	export CUR_PROJECT_PWD := $(shell/bin/pwd)
endif

NAME		:= visual

all : $(NAME)
	@make -C ../
